name: 'Feature Request'
description: 'Suggest an idea or solution to a new Leetcode problem'
body:
    - type: 'markdown'
      attributes:
          value: |-
              > [!IMPORTANT]
              > Thanks for taking the time to suggest an enhancement!
              >
              > Please search **[existing issues](https://github.com/Stewie-pixel/claude-with-leetcode/issues)** to see if a similar feature/solution has already been requested.
    - type: 'textarea'
      id: 'feature'
      attributes:
          label: 'What would you like to be added?'
          description: 'A clear and concise description of the enhancement.'
      validations:
          required: true
    - type: 'textarea'
      id: 'rationale'
      attributes:
          label: 'Why is this needed?'
          description: 'A clear and concise description of why this enhancement is needed.'
      validations:
          required: true
    - type: 'textarea'
      id: 'proof-validation'
      attributes:
          label: 'Evidence of accepted solution on Leetcode'
          description: 'Please provide a link/image to the accepted solution on Leetcode that demonstrates the validated solution.'
      validations:
          required: true
    - type: 'textarea'
      id: 'additional-context'
      attributes:
          label: 'Additional context'
          description: 'Add any other context or screenshots about the feature request here.'
